version: '3'

volumes:
    db_data:
        driver: local
    api_data:
        driver: local
        
services:
    db:
        image: postgres:12.3
        environment: 
            POSTGRES_DB: mobapi
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mob#2020
        ports: 
            - "5432:5432"
        volumes: 
            - "db_data:/var/lib/postgresql/data"
    api:
        build: .
        image: bienemann/mobapi:latest
        ports: 
            - "8080:8080"
        links: 
            - "db:PSQL"
        volumes: 
            - "api_data:/usr/local/api/data"
